const people = require('./people/people.service.js');
const packApplication = require('./pack-application/pack-application.service.js');
const journal = require('./journal/journal.service.js');
const devMilestone = require('./dev-milestone/dev-milestone.service.js');
const chat = require('./chat/chat.service.js');
const broadcast = require('./broadcast/broadcast.service.js');
const forum = require('./forum/forum.service.js');
const users = require('./users/users.service.js');
const savePerson = require('./save-person/save-person.service.js');
const weeklyProgres = require('./weekly-progres/weekly-progres.service.js');
const weeklyProgress = require('./weekly-progress/weekly-progress.service.js');
const profileImg = require('./profile-img/profile-img.service.js');
const profilePix = require('./profile-pix/profile-pix.service.js');
const joinForumChannel = require('./join-forum-channel/join-forum-channel.service.js');
const resetPassword = require('./reset-password/reset-password.service.js');
// eslint-disable-next-line no-unused-vars
module.exports = function (app) {
  app.configure(people);
  app.configure(packApplication);
  app.configure(journal);
  app.configure(devMilestone);
  app.configure(chat);
  app.configure(broadcast);
  app.configure(forum);
  app.configure(users);
  app.configure(savePerson);
  app.configure(weeklyProgres);
  app.configure(weeklyProgress);
  app.configure(profileImg);
  app.configure(profilePix);
  app.configure(joinForumChannel);
  app.configure(resetPassword);
};
